# This is a basic workflow to help you get started with Actions

name: Common push version

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_call:
    inputs:
      level:
        description: "Version level to increase (major, minor or patch)"
        required: false
        default: "minor"
        type: string
      ref:
        description: "Base branch"
        required: false
        default: "main"
        type: string

permissions:
  contents: write
  pull-requests: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  increase_version:
    name: Increase version

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ inputs.ref }}
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .node-version
          package-manager-cache: false

      - name: Prepare git
        run: |
          git config --global "safe.directory" "$GITHUB_WORKSPACE"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config user.name "${GITHUB_ACTOR}"

      - name: Get current version
        id: current-version
        run: |
          echo "version=$(node -p "require('./package.json').version")" >> "$GITHUB_OUTPUT"

      - name: Define next version
        id: define_version
        uses: alfred82santa/action-next-version@a10a6ecf5bd78cf83bd37c718049931878db4f8d # v1.3.0
        with:
          version: ${{ steps.current-version.outputs.version }}
          level: ${{ inputs.level || contains(fromJson('["master", "main"]'), inputs.ref) && 'minor' || (startsWith(inputs.ref, 'release/')) && 'patch' || 'none' }}
          versionFormat: "semver"

      - name: Set new version
        id: set-version
        env:
          NEW_VERSION: ${{ steps.define_version.outputs.version }}
        run: |
          npm version "$NEW_VERSION" --no-git-tag-version --no-commit-hooks

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          title: "Bump version to ${{ steps.define_version.outputs.version }}"
          branch: "task/start-version-${{ steps.define_version.outputs.version }}"
          base: ${{ inputs.ref }}
          delete-branch: true
          commit-message: "Bump version to ${{ steps.define_version.outputs.version }}"
          body: |
            :crown: *Automatic PR starting new version*
          labels: automated,bot
