# This is a basic workflow to help you get started with Actions

name: Common push version

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  workflow_call:
    inputs:
      level:
        description: "Version level to increase (major, minor or patch)"
        required: false
        default: "minor"
        type: string
      ref:
        description: "Base branch"
        required: false
        default: "develop"
        type: string

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  increase_version:
    name: Increase version

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Setup python
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Prepare git
        run: |
          git config --global "safe.directory" "$GITHUB_WORKSPACE"
          git config user.email '${{ github.actor }}@users.noreply.github.com'
          git config user.name '${{ github.actor }}'

      - name: Get current version
        id: current-version
        run: |
          echo "version=$(node -p "require('./package.json').version")" >> "$GITHUB_OUTPUT"

      - name: Define next version
        id: define_version
        uses: alfred82santa/action-next-version@v1
        with:
          version: ${{ steps.current-version.outputs.version }}
          level: ${{ inputs.level || contains(fromJson('["master", "main"]'), inputs.ref) && 'minor' || (startsWith(inputs.ref, 'release/')) && 'patch' || 'none' }}
          versionFormat: "semver"

      - name: Set new version
        id: set-version
        run: |
          npm version ${{ steps.define_version.outputs.version }} --no-git-tag-version --no-commit-hooks

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "Bump version to ${{ steps.define_version.outputs.version }}"
          branch: "task/start-version-${{ steps.define_version.outputs.version }}"
          base: ${{ inputs.ref }}
          delete-branch: true
          commit-message: "Bump version to ${{ steps.define_version.outputs.version }}"
          body: |
            :crown: *Automatic PR starting new version*
          labels: automated,bot
