# This is a basic workflow to help you get started with Actions

name: Increase version

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:
    inputs:
      level:
        description: "Version level to increase (major, minor or patch)"
        required: true
        default: "minor"
        type: choice
        options:
          - patch
          - minor
          - major

      ref:
        description: "Base branch"
        required: false
        default: "main"
        type: string

permissions:
  contents: write
  pull-requests: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  increase_version:
    uses: ./.github/workflows/common-push-version.yml
    with:
      level: ${{ inputs.level }}
      ref: ${{ inputs.ref }}
    secrets: inherit
