name: Push new version to main

on:
  push:
    branches:
      - release/*

run-name: Bump version in main because ${{ github.ref_name }} pushed.

permissions: {}

jobs:
  get_main_version:
    name: Get version in main

    runs-on: ubuntu-latest

    permissions:
      contents: read

    outputs:
      minorVersion: ${{ steps.define_version.outputs.baseReleaseMinor }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: main
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .node-version
          package-manager-cache: false

      - name: Get current version
        id: current-version
        run: |
          echo "version=$(node -p "require('./package.json').version")" >> "$GITHUB_OUTPUT"

      - name: Define release version
        id: define_version
        uses: alfred82santa/action-next-version@a10a6ecf5bd78cf83bd37c718049931878db4f8d # v1.3.0
        with:
          version: ${{ steps.current-version.outputs.version }}
          level: "none"
          versionFormat: "semver"

  increase_version:
    needs:
      - get_main_version
    if: endsWith(github.ref_name, needs.get_main_version.outputs.minorVersion)
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/common-push-version.yml # zizmor: ignore[self-repository]
    with:
      level: "minor"
      ref: main
